apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-webapp
spec:
  tls:
      - hosts:
        - 34.16.120.13
        secretName: optimove-app-tls
  ingressClassName: nginx
  rules:
    - http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: {{ .Release.Name }}-webapp
              port:
                number: 80
